"""add agent runs tool call logs and agent memory tables

Revision ID: 5d17479735ac
Revises: e3a7c5d89f12
Create Date: 2026-10-06 12:12:18.884123

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5d17479735ac'
down_revision: str | None = 'e3a7c5d89f12'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_run_id'), 'agent_runs', ['agent_run_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_type'), 'agent_runs', ['task_type'], unique=False)
    op.create_index(op.f('ix_agent_runs_trace_id'), 'agent_runs', ['trace_id'], unique=False)
    op.create_table('agent_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('source_run_id', sa.String(length=64), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_course_id'), 'agent_memory', ['course_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_memory_type'), 'agent_memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_agent_memory_user_id'), 'agent_memory', ['user_id'], unique=False)
    op.create_table('tool_call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_run_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('args_summary', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.agent_run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_logs_agent_run_id'), 'tool_call_logs', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_trace_id'), 'tool_call_logs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_call_logs_trace_id'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_agent_run_id'), table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    op.drop_index(op.f('ix_agent_memory_user_id'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_memory_type'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_course_id'), table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index(op.f('ix_agent_runs_trace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_task_type'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_run_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
