"""add votes tables and reputation logs with vote score columns

Revision ID: ac5af405a45e
Revises: a44b1c09079e
Create Date: 2026-10-02 17:46:41.463760

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ac5af405a45e'
down_revision: str | None = 'a44b1c09079e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_logs_course_id'), 'reputation_logs', ['course_id'], unique=False)
    op.create_index(op.f('ix_reputation_logs_user_id'), 'reputation_logs', ['user_id'], unique=False)
    op.create_table('question_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_question_votes_pair')
    )
    op.create_index(op.f('ix_question_votes_question_id'), 'question_votes', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_votes_user_id'), 'question_votes', ['user_id'], unique=False)
    op.create_table('answer_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'user_id', name='uq_answer_votes_pair')
    )
    op.create_index(op.f('ix_answer_votes_answer_id'), 'answer_votes', ['answer_id'], unique=False)
    op.create_index(op.f('ix_answer_votes_user_id'), 'answer_votes', ['user_id'], unique=False)
    op.add_column('answers', sa.Column('vote_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('questions', sa.Column('vote_score', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # 三张表的索引被各自 FK 依赖（MySQL 1553：needed in a foreign key constraint），
    # 随整表删除，不单独 drop（T-07 踩坑惯例）
    op.drop_column('questions', 'vote_score')
    op.drop_column('answers', 'vote_score')
    op.drop_table('answer_votes')
    op.drop_table('question_votes')
    op.drop_table('reputation_logs')
    # ### end Alembic commands ###
