"""add answers table and question accepted answer

Revision ID: f9c6a0c48f93
Revises: 614ffbaac7c4
Create Date: 2026-09-30 11:39:15.586482

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f9c6a0c48f93'
down_revision: str | None = '614ffbaac7c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('recommended_by_assistant', sa.Boolean(), nullable=False),
    sa.Column('certified_by_teacher', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_author_id'), 'answers', ['author_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.add_column('questions', sa.Column('accepted_answer_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(
        'uq_questions_accepted_answer_id', 'questions', ['accepted_answer_id']
    )
    op.create_foreign_key(
        'fk_questions_accepted_answer_id', 'questions', 'answers',
        ['accepted_answer_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_questions_accepted_answer_id', 'questions', type_='foreignkey')
    op.drop_constraint('uq_questions_accepted_answer_id', 'questions', type_='unique')
    op.drop_column('questions', 'accepted_answer_id')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_author_id'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
